from modules.authenticate import autenticar_usuario
from modules.delete_id import deletar_registro
from modules.edit_id import editar_registro
from modules.insert_func import inserir_dados_func
from modules.insert_uso import inserir_dados_uso
from modules.register_log import registrar_log
from modules.search import buscar_registros
from modules.validation import validar_csv
from modules.load_data import carregar_dados